### ISSUE TITLE
Nice job!

### ISSUE THREAD

**Issue by michelollivier** [kleinejan/titatoggle#10]
Nice job. Is it possible to turn radio buttons into switches. I use bootstrap switch but I would prefer a pure less solution. Thank you.

**Comment by kleinejan** [comment]
Hi Michel,
currently you only can use checkboxes. This is because a switch behaviour is only possible with radio buttons when you use 2 radio buttons. You can not "uncheck" a radio button. Semantically a checkbox is preferably. 
But perhaps is some case it is not possible to use a checbox (cms/backend). 
I will put it on the backlog and make a toggle button for a pair of radiobuttons.

**Comment by michelollivier** [comment]
Hi Jan,Thanks a lot
Regds M

---- On Wed, 15 Jun 2016 10:30:46 +0200 Jan Enning&lt;notifications@github.com&gt; wrote ---- 

Hi Michel,
 currently you only can use checkboxes. This is because a switch behaviour is only possible with radio buttons when you use 2 radio buttons. You can not "uncheck" a radio button. Semantically a checkbox is preferably. 
 But perhaps is some case it is not possible to use a checbox (cms/backend). 
 I will put it on the backlog and make a toggle button for a pair of radiobuttons.
